name: Update badges

on:
  schedule:
    # Runs at 11:00pm Every Day
    - cron: "0 22 * * *"
jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@main
          CREDLY_USER:"lrpadget1@gmail.com"
