name: Update badges

on:
  schedule:
  - cron: "20 19 * * *"
jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@main
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          CREDLY_USER: lrpadget1@gmail.com
          COMMIT_MESSAGE: "Updating my credly badges"
